checkpoint_01:
  valve_properties:
    height: 0.02
    length: 0.15
    width: 0.03
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: -0.0
        arm2: 0.98
        arm3: -1.27
        arm4: -2.21
        arm5: 1.88
      arm1: 3.1
      arm2: 0.98
      arm3: -1.27
      arm4: -2.21
      arm5: 1.88
    endeffectorPosition:
    - frame_id: world
      q_w: -0.07826203107833862
      q_x: -0.050887417048215866
      q_y: 0.001647965982556343
      q_z: 0.9956321120262146
      x: 3.505504608154297
      y: 2.152069091796875
      z: 0.567916214466095
    flipper_angle: -0.75
    x: 0.5
    y: -0.8
    yaw: 1.5
  max_value: 1
  min_value: 0
  wallOrientation: 1
checkpoint_02:
  dial_properties:
    min_angle: 0.52
    max_angle: 5.76
    diameter: 0.1
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 3.1
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: 0.014741217717528343
      q_x: -0.11937817186117172
      q_y: 0.17420725524425507
      q_z: 0.9773352742195129
      x: 3.3907992839813232
      y: 1.9053535461425781
      z: 0.9246250987052917
    flipper_angle: -0.1500000000000001
    x: 0.77
    y: -0.5
    yaw: 1.5
  max_value: 0.6
  min_value: 0
  wallOrientation: 1
checkpoint_03:
  dial_properties:
    min_angle: 0.52
    max_angle: 5.76
    diameter: 0.1
  distanceToWall: 0.19
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: -0.9691466689109802
      q_x: 0.24183595180511475
      q_y: 0.013860015198588371
      q_z: 0.04558631777763367
      x: 0.8380609154701233
      y: 1.8185174465179443
      z: 0.7967530488967896
    flipper_angle: -0.75
    x: -0.7
    y: 0.1
    yaw: 0.5
  max_value: 1
  min_value: 0
  wallOrientation: 0
checkpoint_04:
  dial_properties:
    min_angle: 0.52
    max_angle: 5.76
    diameter: 0.1
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 0
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: -0.8051276206970215
      q_x: -0.022108815610408783
      q_y: 0.019265400245785713
      q_z: 0.592376172542572
      x: 1.2985354661941528
      y: 2.469597578048706
      z: 1.4434475898742676
    flipper_angle: -0.75
    x: 0.0
    y: 0.9
    yaw: 2.0
  - armPosition:
    - arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: -0.96
      arm5: 0
    flipper_angle: -0.75
    x: 0.1
    y: -1.1
    yaw: 0.5
  max_value: 2.5
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_05:
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  distanceToWall: 0.1
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 3.1415800746905447
        arm2: 0.41919432144832847
        arm3: -2.1324733970826903
        arm4: -0.9596600422674246
        arm5: 1.5707388237618911
      arm1: 3.14
      arm2: 0.42
      arm3: -2.13
      arm4: -0.96
      arm5: 1.57
    endeffectorPosition:
    - frame_id: world
      q_w: 0.002667376771569252
      q_x: -0.10886725783348083
      q_y: 0.055061668157577515
      q_z: 0.9925270676612854
      x: 0.6526914238929749
      y: 2.719726324081421
      z: 0.9593002796173096
    flipper_angle: -0.1
    x: 1.45
    y: -0.0
    yaw: 1.0
  max_value: 1
  min_value: 0
  wallOrientation: 0.5
checkpoint_06:
  dial_properties:
    min_angle: 0.52
    max_angle: 5.76
    diameter: 0.1
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: 0.7021603584289551
      q_x: 0.0503336638212204
      q_y: 0.09989340603351593
      q_z: 0.7031775712966919
      x: 2.2620913982391357
      y: 0.5669023394584656
      z: 1.2838525772094727
    flipper_angle: -0.2
    x: -0.2
    y: -1.25
    yaw: 2.0
  max_value: 10
  min_value: 0
  wallOrientation: -0.5
checkpoint_07:
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: 0.7
      q_x: -0.01
      q_y: 0.04
      q_z: 0.71
      x: 1.95
      y: 0.49
      z: 1.13
    flipper_angle: -0.4
    x: -0.6
    y: -0.85
    yaw: 2.0
  max_value: 100
  min_value: 0
  wallOrientation: -0.5
