checkpoint_01:
  armPosition:
  - arm1: -1.5100054035346675
    arm2: 0.4239743911273841
    arm3: -1.9025616194885
    arm4: -2.357278073127927
    arm5: -1.0692365895530944
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - arm1: -1.51
      arm2: 0.42
      arm3: -1.9
      arm4: -2.36
      arm5: -1.07
    flipper_angle: -0.75
    x: 0.9
    y: -0.3
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 0.7
    y: -1.2
    yaw: 1.5
  max_value: 10
  min_value: 0
  wallOrientation: 1
checkpoint_02:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 1.8
    y: 0.0
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 1.8
    y: 0.0
    yaw: 1.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 1.6
    y: -1.7
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 1.6
    y: -1.7
    yaw: 1.5
  max_value: 2.5
  min_value: 0
  wallOrientation: 1
checkpoint_03:
  armPosition:
  - arm1: 0.00032213670167724473
    arm2: -0.912378539357495
    arm3: -2.300450629554555
    arm4: -0.9609690902185841
    arm5: -8.427760695539632e-06
  dial_properties:
    diameter: 0.15
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: -2.0
      arm3: -2.3
      arm4: -0.96
      arm5: 0.0
    flipper_angle: -0.75
    x: 0.0
    y: -1.8
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 0.7
    y: -1.8
    yaw: 1.0
  max_value: 10
  min_value: 0
  wallOrientation: 0.5
checkpoint_04:
  distanceToWall: 0.19
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: -0.4
    y: -1.1
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: -0.35
    y: 1.1
    yaw: 0.20555555555555555
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: -0.4
    y: -1.1
    yaw: 1.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: -0.35
    y: 1.1
    yaw: 1.2055555555555555
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0
checkpoint_05:
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 1.1
    y: -0.4
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 1.1
    y: -0.4
    yaw: 1.0
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_06:
  distanceToWall: 0.1
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 1.1
    y: -0.4
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 1.1
    y: -0.4
    yaw: 1.0
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_07:
  dial_properties:
    diameter: 0.1
  distanceToWall: -0.13
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: -0.1
    y: 0.5
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.5
    yaw: 1.0
  max_value: 2.5
  min_value: 0
  wallOrientation: -0.5
checkpoint_08:
  dial_properties:
    diameter: 0.105
  distanceToWall: -0.62
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 0.0
    y: 1.1
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 0.0
    y: 1.1
    yaw: 1.0
  max_value: 16
  min_value: 0
  wallOrientation: -0.5
checkpoint_09:
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.6
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.6
    yaw: 1.0
  max_value: 100
  min_value: 0
  wallOrientation: -0.5
