checkpoint_01:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.9
    y: -1.1
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.9
    y: -1.1
    yaw: 1.5
  max_value: 10
  min_value: 0
  wallOrientation: 1
checkpoint_02:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.76
    y: 0.0
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.76
    y: 0.0
    yaw: 1.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.8
    y: -1.35
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.8
    y: -1.35
    yaw: 1.5
  max_value: 2.5
  min_value: 0
  wallOrientation: 1
checkpoint_03:
  dial_properties:
    diameter: 0.15
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: -0.96
      arm5: 0.0
    x: 0.0
    y: -1.88
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.7
    y: -1.88
    yaw: 1.0
  max_value: 10
  min_value: 0
  wallOrientation: 0.5
checkpoint_04:
  distanceToWall: 0.19
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: -0.46
    y: -1.0
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: -0.35
    y: 1.1
    yaw: 0.20555555555555555
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: -0.46
    y: -1.0
    yaw: 1.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: -0.35
    y: 1.1
    yaw: 1.2055555555555555
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0
checkpoint_05:
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.1
    y: -0.43
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.1
    y: -0.43
    yaw: 1.0
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_06:
  distanceToWall: 0.1
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.1
    y: -0.42
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.1
    y: -0.42
    yaw: 1.0
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_07:
  dial_properties:
    diameter: 0.1
  distanceToWall: -0.13
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: -0.1
    y: 0.52
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.0
    y: 0.52
    yaw: 1.0
  max_value: 2.5
  min_value: 0
  wallOrientation: -0.5
checkpoint_08:
  dial_properties:
    diameter: 0.105
  distanceToWall: -0.62
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.0
    y: 1.02
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.0
    y: 1.02
    yaw: 1.0
  max_value: 16
  min_value: 0
  wallOrientation: -0.5
checkpoint_09:
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.0
    y: 0.68
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.0
    y: 0.68
    yaw: 1.0
  max_value: 100
  min_value: 0
  wallOrientation: -0.5
