checkpoint_01:
  armPosition:
  - arm1: 0.00011697824524681266
    arm2: 0.0923200329040732
    arm3: -0.6332604753035982
    arm4: -0.661815399273296
    arm5: 0.9424791914900261
  - arm1: 0.0
    arm2: 0
    arm3: 0.0
    arm4: 0
    arm5: 0
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.09
      arm3: -0.63
      arm4: -0.66
      arm5: 0.94
    - arm1: 0.0
      arm2: 0
      arm3: 0.0
      arm4: 0
      arm5: 0
    flipper_angle: -1.57
    x: 0.5
    y: -0.1
    yaw: 1.5
  - armPosition:
    - arm1: 3.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    - arm1: 1.0
      arm2: 0
      arm3: 0.0
      arm4: 0
      arm5: 0
    - arm1: 0.0
      arm2: 7.0
      arm3: 0
      arm4: 8.0
      arm5: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.0
    yaw: 0.0
  max_value: 10
  min_value: 0
  wallOrientation: 1
checkpoint_02:
  armPosition:
  - arm1: -5.9721554422687007e-05
    arm2: 0.5188883123243899
    arm3: -1.4387882108441987
    arm4: 1.1025372820036612
    arm5: -1.6336360486682207
  - arm1: 0.0
    arm2: 0
    arm3: 0.0
    arm4: 0
    arm5: 0
  - arm1: 0.0
    arm2: 0
    arm3: 0
    arm4: 0
    arm5: 0
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.52
      arm3: -1.44
      arm4: 1.1
      arm5: -1.63
    - arm1: 0.0
      arm2: 0
      arm3: 0.0
      arm4: 0
      arm5: 0
    - arm1: 0.0
      arm2: 0
      arm3: 0
      arm4: 0
      arm5: 0
    flipper_angle: -1.57
    x: 0.8
    y: 0.0
    yaw: 1.5
  max_value: 2.5
  min_value: 0
  wallOrientation: 1
checkpoint_03:
  armPosition:
  - arm1: 2.412995967038256e-05
    arm2: 0.8832576360913871
    arm3: -1.3798786611656286
    arm4: 0.9374405052086372
    arm5: 1.5707933807867063
  - arm1: 2.0
    arm2: 0
    arm3: 0.0
    arm4: 0
    arm5: 0
  distanceToWall: 0.19
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.88
      arm3: -1.38
      arm4: 0.94
      arm5: 1.57
    - arm1: 2.0
      arm2: 0
      arm3: 0.0
      arm4: 0
      arm5: 0
    flipper_angle: -1.57
    x: -0.7
    y: -0.1
    yaw: 0.5
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0
checkpoint_04:
  armPosition:
  - arm1: -0.5654880368907191
    arm2: 0.1019890814414266
    arm3: -0.8017520262834514
    arm4: 0.6061578703000636
    arm5: -8.822453452239643e-07
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - arm1: -0.57
      arm2: 0.1
      arm3: -0.8
      arm4: 0.61
      arm5: 0.0
    flipper_angle: -0.75
    x: 0.0
    y: 0.9
    yaw: 2.0
  - armPosition:
    - arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: -0.96
      arm5: 0
    flipper_angle: -0.75
    x: 0.1
    y: -1.1
    yaw: 0.5
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_05:
  armPosition:
  - arm1: 1.5079357922878698
    arm2: -0.2337046930328981
    arm3: -1.902375015240211
    arm4: -1.4891820176889778
    arm5: 1.570796101559357
  distanceToWall: 0.1
  driveToPosition:
  - armPosition:
    - arm1: 1.51
      arm2: -0.23
      arm3: -1.9
      arm4: -1.49
      arm5: 1.57
    flipper_angle: -0.75
    x: 0.7
    y: -0.1
    yaw: 0.2777777777777778
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_09:
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - arm1: 1.0
      arm2: 0.0
      arm3: 1.23
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: -1.0999999999999999
    y: -2.3
    yaw: 2.0
  max_value: 100
  min_value: 0
  wallOrientation: -0.5
