checkpoint_01:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: -3.1720548010483185e-06
        arm2: 0.27994023986242844
        arm3: -2.3014024401273234
        arm4: -0.9596686630499764
        arm5: 1.6335660161411978
      arm1: -3.1720548010483185e-06
      arm2: 0.28
      arm3: -2.3
      arm4: -0.96
      arm5: 1.63
    endeffectorPosition:
    - frame_id: world
      q_w: 0.98
      q_x: 0
      q_y: -0.21
      q_z: -0.0
      x: -1.28
      y: -0.65
      z: -1.77
    flipper_angle: -0.75
    x: 0.5
    y: -0.6
    yaw: 1.5
    flipper_angle: -0.75
    x: 0.0
    y: 0.0
    yaw: 0.0
  max_value: 10
  min_value: 0
  wallOrientation: 1
checkpoint_02:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.06
        arm2: -1.81
        arm3: -2.59
        arm4: 0.5
        arm5: 1.45
    - arm1: 0.06
      arm2: -1.81
      arm3: -2.59
      arm4: 0.5
      arm5: 1.45
    endeffectorPosition:
    - frame_id: world
      q_w: 0.98
      q_x: 0
      q_y: -0.21
      q_z: -0.0
      x: -1.28
      y: -0.65
      z: -1.77
    flipper_angle: -1.57
    x: 0.77
    y: 0.0
    yaw: 1.5
  max_value: 2.5
  min_value: 0
  wallOrientation: 1
checkpoint_03:
  armPosition:
  - arm1: 2.412995967038256e-05
    arm2: 0.8832576360913871
    arm3: -1.3798786611656286
    arm4: 0.9374405052086372
    arm5: 1.5707933807867063
  - arm1: 2.0
    arm2: 0
    arm3: 0.0
    arm4: 0
    arm5: 0
  distanceToWall: 0.19
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.88
      arm3: -1.38
      arm4: 0.94
      arm5: 1.57
    - arm1: 2.0
      arm2: 0
      arm3: 0.0
      arm4: 0
      arm5: 0
    flipper_angle: -1.57
    x: -0.7
    y: -0.1
    yaw: 0.5
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0
checkpoint_04:
  armPosition:
  - arm1: -0.5654880368907191
    arm2: 0.1019890814414266
    arm3: -0.8017520262834514
    arm4: 0.6061578703000636
    arm5: -8.822453452239643e-07
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - arm1: -0.57
      arm2: 0.1
      arm3: -0.8
      arm4: 0.61
      arm5: 0.0
    flipper_angle: -0.75
    x: 0.0
    y: 0.9
    yaw: 2.0
  - armPosition:
    - arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: -0.96
      arm5: 0
    flipper_angle: -0.75
    x: 0.1
    y: -1.1
    yaw: 0.5
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_05:
  armPosition:
  - arm1: 1.5079357922878698
    arm2: -0.2337046930328981
    arm3: -1.902375015240211
    arm4: -1.4891820176889778
    arm5: 1.570796101559357
  distanceToWall: 0.1
  driveToPosition:
  - armPosition:
    - arm1: 1.51
      arm2: -0.23
      arm3: -1.9
      arm4: -1.49
      arm5: 1.57
    flipper_angle: -0.75
    x: 0.55
    y: -0.7
    yaw: 0.5
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_09:
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - arm1: 1.0
      arm2: 0.0
      arm3: 1.23
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: -1.0999999999999999
    y: -2.3
    yaw: 2.0
  max_value: 100
  min_value: 0
  wallOrientation: -0.5
