checkpoint_01:
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: -0.0
        arm2: 0.98
        arm3: -1.27
        arm4: -2.21
        arm5: 1.88
      arm1: 3.1
      arm2: 0.98
      arm3: -1.27
      arm4: -2.21
      arm5: 1.88
    endeffectorPosition:
    - frame_id: world
      q_w: -0.08
      q_x: -0.05
      q_y: 0.001647965982556343
      q_z: 1.0
      x: 3.51
      y: 2.15
      z: 0.57
    flipper_angle: -0.75
    x: 0.5
    y: -0.8
    yaw: 1.5
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.02
    length: 0.15
    width: 0.03
  wallOrientation: 1
checkpoint_02:
  dial_properties:
    diameter: 0.1
    max_angle: 5.76
    min_angle: 0.52
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 3.1
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: 0.01
      q_x: -0.12
      q_y: 0.17
      q_z: 0.98
      x: 3.39
      y: 1.91
      z: 0.92
    flipper_angle: -0.15
    x: 0.77
    y: -0.5
    yaw: 1.5
  max_value: 0.6
  min_value: 0
  wallOrientation: 1
checkpoint_03:
  dial_properties:
    diameter: 0.1
    max_angle: 5.76
    min_angle: 0.52
  distanceToWall: 0.19
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: 1.0
      q_x: 0.0
      q_y: 0.2
      q_z: 0.0
      x: 0.6
      y: 1.65
      z: 0.9
    flipper_angle: -0.75
    x: -0.7
    y: 0.8999999999999999
    yaw: 0.5
  max_value: 1
  min_value: 0
  wallOrientation: 0
checkpoint_04:
  dial_properties:
    diameter: 0.1
    max_angle: 5.76
    min_angle: 0.52
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 0
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: -0.81
      q_x: -0.02
      q_y: 0.02
      q_z: 0.59
      x: 1.3
      y: 2.47
      z: 1.44
    flipper_angle: -0.75
    x: 0.0
    y: 0.9
    yaw: 2.0
  - armPosition:
    - arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: -0.96
      arm5: 0
    flipper_angle: -0.75
    x: 0.1
    y: -1.1
    yaw: 0.5
  max_value: 2.5
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_05:
  distanceToWall: 0.1
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 3.1415800746905447
        arm2: 0.41919432144832847
        arm3: -2.1324733970826903
        arm4: -0.9596600422674246
        arm5: 1.5707388237618911
      arm1: 3.14
      arm2: 0.42
      arm3: -2.13
      arm4: -0.96
      arm5: 1.57
    endeffectorPosition:
    - frame_id: world
      q_w: 0.0
      q_x: -0.21000000000000002
      q_y: 0.06
      q_z: 0.99
      x: 0.65
      y: 2.7
      z: 0.96
    flipper_angle: -0.1
    x: 1.45
    y: 0.0
    yaw: 1.0
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_06:
  dial_properties:
    diameter: 0.1
    max_angle: 5.76
    min_angle: 0.52
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: 1.0
      q_x: 0.0
      q_y: 0.0
      q_z: 1.3
      x: 2.56
      y: 0.57
      z: 1.28
    flipper_angle: -0.2
    x: -0.2
    y: -1.05
    yaw: 2.0
  max_value: 10
  min_value: 0
  wallOrientation: -0.5
checkpoint_07:
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: 0.7
      q_x: -0.01
      q_y: 0.04
      q_z: 0.71
      x: 1.95
      y: 0.49
      z: 1.13
    flipper_angle: -0.4
    x: -0.6
    y: -0.85
    yaw: 2.0
  max_value: 100
  min_value: 0
  wallOrientation: -0.5
checkpoint_09:
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 0
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: -0.81
      q_x: -0.02
      q_y: 0.02
      q_z: 0.59
      x: 1.3
      y: 2.47
      z: 1.44
    flipper_angle: -0.75
    x: 0.0
    y: 0.9
    yaw: 2.0
  - armPosition:
    - arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: -0.96
      arm5: 0
    flipper_angle: -0.75
    x: 0.1
    y: -1.1
    yaw: 0.5
  max_value: 2.5
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5