checkpoint_01:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: -0.0
        arm2: 0.98
        arm3: -1.27
        arm4: -2.21
        arm5: 1.88
      arm1: 3.1
      arm2: 0.98
      arm3: -1.27
      arm4: -2.21
      arm5: 1.88
    endeffectorPosition:
    - frame_id: world
      q_w: 0.98
      q_x: 0
      q_y: -0.21
      q_z: -0.0
      x: -1.28
      y: -0.65
      z: -1.77
    flipper_angle: -0.75
    x: 0.5
    y: -0.8
    yaw: 1.5
  max_value: 10
  min_value: 0
  wallOrientation: 1
checkpoint_02:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 3.1
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    endeffectorPosition:
    - frame_id: world
      q_w: -0.13
      q_x: 0.03
      q_y: 0.24
      q_z: 0.96
      x: 3.53
      y: 1.84
      z: 0.8
    flipper_angle: -0.75
    x: 0.77
    y: 0.0
    yaw: 1.5
  max_value: 2.5
  min_value: 0
  wallOrientation: 1
checkpoint_03:
  distanceToWall: 0.19
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0
        arm2: -0.91
        arm3: -2.3
        arm4: 1.6
        arm5: 1.7
      arm1: 0
      arm2: -0.91
      arm3: -2.3
      arm4: 1.6
      arm5: 1.7
    flipper_angle: -0.75
    x: -0.7
    y: 0.1
    yaw: 0.5
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0
checkpoint_04:
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - arm1: -0.57
      arm2: 0.1
      arm3: -0.8
      arm4: 0.61
      arm5: 0.0
    flipper_angle: -0.75
    x: 0.0
    y: 0.9
    yaw: 2.0
  - armPosition:
    - arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: -0.96
      arm5: 0
    flipper_angle: -0.75
    x: 0.1
    y: -1.1
    yaw: 0.5
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_05:
  distanceToWall: 0.1
  driveToPosition:
  - armPosition:
    - arm1: 1.51
      arm2: -0.23
      arm3: -1.9
      arm4: -1.49
      arm5: 1.57
    flipper_angle: -0.75
    x: 0.55
    y: -0.7
    yaw: 0.5
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_06:
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - arm1: 1.0
      arm2: 0.0
      arm3: 1.23
      arm4: 0.0
      arm5: 0
    flipper_angle: -0.75
    x: 0.3999999999999999
    y: -1.25
    yaw: 2.0
  max_value: 100
  min_value: 0
  wallOrientation: -0.5
