checkpoint_01:
  armPosition:
  - arm1: -1.2643456308409107
    arm2: 0.796602546537728
    arm3: -1.098627655867947
    arm4: -1.6286791833335847
    arm5: -0.18849341569105782
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - arm1: -1.26
      arm2: 0.8
      arm3: -1.1
      arm4: -1.63
      arm5: -0.19
    x: 0.7
    y: -1.2
    yaw: 0.5
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.7
    y: -1.2
    yaw: 1.5
    flipper_angle: -0.75
  max_value: 10
  min_value: 0
  wallOrientation: 1
checkpoint_02:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.8
    y: 0.0
    yaw: 0.5
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.8
    y: 0.0
    yaw: 1.5
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.6
    y: -1.7
    yaw: 0.5
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.6
    y: -1.7
    yaw: 1.5
    flipper_angle: -0.75
  max_value: 2.5
  min_value: 0
  wallOrientation: 1
checkpoint_03:
  armPosition:
  - arm1: 0.00032213670167724473
    arm2: -0.912378539357495
    arm3: -2.300450629554555
    arm4: -0.9609690902185841
    arm5: -8.427760695539632e-06
  dial_properties:
    diameter: 0.15
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: -2.0
      arm3: -2.3
      arm4: -0.96
      arm5: 0.0
    x: 0.0
    y: -1.8
    yaw: 0.0
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.7
    y: -1.8
    yaw: 1.0
    flipper_angle: -0.75
  max_value: 10
  min_value: 0
  wallOrientation: 0.5
checkpoint_04:
  distanceToWall: 0.19
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: -0.4
    y: -1.1
    yaw: 0.5
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: -0.35
    y: 1.1
    yaw: 0.20555555555555555
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: -0.4
    y: -1.1
    yaw: 1.5
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: -0.35
    y: 1.1
    yaw: 1.2055555555555555
    flipper_angle: -0.75
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0
checkpoint_05:
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.1
    y: -0.4
    yaw: 0.0
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.1
    y: -0.4
    yaw: 1.0
    flipper_angle: -0.75
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_06:
  distanceToWall: 0.1
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.1
    y: -0.4
    yaw: 0.0
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 1.1
    y: -0.4
    yaw: 1.0
    flipper_angle: -0.75
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_07:
  dial_properties:
    diameter: 0.1
  distanceToWall: -0.13
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: -0.1
    y: 0.5
    yaw: 0.0
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.0
    y: 0.5
    yaw: 1.0
    flipper_angle: -0.75
  max_value: 2.5
  min_value: 0
  wallOrientation: -0.5
checkpoint_08:
  dial_properties:
    diameter: 0.105
  distanceToWall: -0.62
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.0
    y: 1.1
    yaw: 0.0
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.0
    y: 1.1
    yaw: 1.0
    flipper_angle: -0.75
  max_value: 16
  min_value: 0
  wallOrientation: -0.5
checkpoint_09:
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.0
    y: 0.6
    yaw: 0.0
    flipper_angle: -0.75
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    x: 0.0
    y: 0.6
    yaw: 1.0
    flipper_angle: -0.75
  max_value: 100
  min_value: 0
  wallOrientation: -0.5
