checkpoint_01:
  armPosition:
  - arm1: -1.5100054035346675
    arm2: 0.4239743911273841
    arm3: -1.9025616194885
    arm4: -2.357278073127927
    arm5: -1.0692365895530944
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 1.6
        arm2: 0.14
        arm3: -2.19
        arm4: -2.36
        arm5: -0.61
      arm1: -1.51
      arm2: 0.42
      arm3: -1.9
      arm4: -2.36
      arm5: -1.07
    endeffectorPosition:
    - frame_id: world
      q_w: 0.98
      q_x: 0
      q_y: -0.21
      q_z: -0.0
      x: -1.28
      y: -0.65
      z: -1.77
    - frame_id: base_link
      q_w: 0.98
      q_x: 0
      q_y: -0.21
      q_z: 0.0
      x: 0.13
      y: 0.06
      z: -0.94
    flipper_angle: -0.75
    x: 0.9
    y: -0.3
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.7
    y: -1.2
    yaw: 1.5
  max_value: 10
  min_value: 0
  default_min_value: 1
  default_max_value: 2
  wallOrientation: 1
checkpoint_02:
  armPosition:
  - arm1: -1.0681418642327056
    arm2: 0.5567713524402933
    arm3: -1.4974757823670863
    arm4: -2.2060869326393924
    arm5: 0.6911516775803515
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 2.46
        arm2: 0.26
        arm3: -1.99
        arm4: -2.39
        arm5: 1.00
      arm1: -0.68
      arm2: 0.26
      arm3: -1.99
      arm4: -2.39
      arm5: 1.00
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 1.8
    y: -0.5
    yaw: 0.5
  max_value: 2.5
  min_value: 0
  default_min_value: 1
  default_max_value: 1.5
  wallOrientation: 1
checkpoint_03:
  armPosition:
  - alternative:
    - arm1: -1.7
      arm2: 0.99
      arm3: -0.46
      arm4: -1.27
      arm5: 0.5
    arm1: -1.445132124937139
    arm2: -0.9943656011032518
    arm3: -2.2926332892833905
    arm4: -0.9603236701157964
    arm5: -5.79014574064729e-07
  dial_properties:
    diameter: 0.15
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 1.5
        arm2: -0.12
        arm3: -2.07
        arm4: -1.94
        arm5: 0.0
      arm1: -1.64
      arm2: -0.12
      arm3: -2.07
      arm4: -1.94
      arm5: 0.0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: -1.88
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.7
    y: -1.8
    yaw: 1.0
  max_value: 10
  min_value: 0
  default_min_value: 1
  default_max_value: 2
  wallOrientation: 0.5
checkpoint_04:
  armPosition:
  - alternative:
    - arm1: 0.0
      arm2: -0.37
      arm3: 1.27
      arm4: -2.65
      arm5: 0.38
    arm1: -1.2318588540338737e-05
    arm2: 0.14599759055157513
    arm3: -1.842216514663784
    arm4: -0.9601519210180012
    arm5: -6.504075129143416e-06
  - arm1: 3.14
    arm2: 0.93
    arm3: -1.56
    arm4: 0.94
    arm5: -1.76
  distanceToWall: 0.19
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.0
        arm2: -0.37
        arm3: 1.27
        arm4: -2.65
        arm5: 0.38
      arm1: 0.0
      arm2: 0.15
      arm3: -1.84
      arm4: -0.96
      arm5: 0.0
    - arm1: 3.14
      arm2: 0.93
      arm3: -1.56
      arm4: 0.94
      arm5: -1.76
    endeffectorPosition:
    - frame_id: world
      q_w: 0.0
      q_x: 0.0
      q_y: 0.0
      q_z: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    flipper_angle: -0.75
    x: -0.46
    y: -1.0
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: -0.35
    y: 1.1
    yaw: 0.20555555555555555
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: -0.4
    y: -1.1
    yaw: 1.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: -0.35
    y: 1.1
    yaw: 1.2055555555555555
  max_value: 1
  min_value: 0
  default_min_value: 0
  default_max_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0
checkpoint_05:
  armPosition:
  - arm1: -0.06077499944584819
    arm2: 0.7923841552726891
    arm3: -1.2086440922893438
    arm4: 1.047685896681628
    arm5: -1.570003154893267
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: -0.06
        arm2: 0.79
        arm3: -1.21
        arm4: 1.05
        arm5: -1.57
      arm1: 0.0
      arm2: -0.37
      arm3: 1.27
      arm4: -2.65
      arm5: 0.38
    endeffectorPosition:
    - frame_id: world
      q_w: 0.0
      q_x: 0.0
      q_y: 0.0
      q_z: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    flipper_angle: -0.75
    x: 1.2
    y: -0.38
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 1.1
    y: -0.4
    yaw: 1.0
  max_value: 1
  min_value: 0
  default_min_value: 0
  default_max_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_06:
  armPosition:
  - alternative:
    - arm1: 0.25
      arm2: -0.05
      arm3: -1.55
      arm4: -1.16
      arm5: -0.0
    arm1: -3.202091788789829e-05
    arm2: -0.38113643398013597
    arm3: 0.7508651479064206
    arm4: -2.650226761655503
    arm5: 0.38000028086182613
  distanceToWall: 0.1
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.25
        arm2: -0.05
        arm3: -1.55
        arm4: -1.16
        arm5: -0.0
      arm1: 0.0
      arm2: -0.38
      arm3: 0.75
      arm4: -2.65
      arm5: 0.38
    endeffectorPosition:
    - frame_id: world
      q_w: 0.0
      q_x: 0.0
      q_y: 0.0
      q_z: 1.0
      x: 0.0
      y: 0.0
      z: 0.0
    flipper_angle: -0.75
    x: 1.2
    y: -0.32999999999999996
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 1.1
    y: -0.4
    yaw: 1.0
  max_value: 1
  min_value: 0
  default_min_value: 1
  default_max_value: 1
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_07:
  armPosition:
  - arm1: 2.701770825802706
    arm2: -0.9300157170892938
    arm3: -1.9599757576943384
    arm4: -1.3200024169301958
    arm5: 1.6300009337755874
  dial_properties:
    diameter: 0.1
  distanceToWall: -0.13
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.14
        arm2: -1.30
        arm3: -1.85
        arm4: -0.60
        arm5: 1.63  
      arm1: -0.04
      arm2: -0.94
      arm3: -1.83
      arm4: -0.93
      arm5: -1.68
    endeffectorPosition:
    - frame_id: world
      q_w: 0.86
      q_x: -0.12
      q_y: 0.08
      q_z: -0.49
      x: 3.02
      y: 4.4
      z: 1.33
    flipper_angle: -0.75
    x: -0.1
    y: 0.6
    yaw: 0.0
#  - armPosition:
#    - arm1: 0.0
#      arm2: 0.0
#      arm3: 0.0
#      arm4: 0.0
#      arm5: 0
#    endeffectorPosition:
#    - frame_id: world
#      q_w: 0
#      q_x: 0
#      q_y: 0
#      q_z: 0
#      x: 0
#      y: 0
#      z: 0
#    flipper_angle: -0.75
#    x: 0.0
#    y: 0.5
#    yaw: 1.0
  max_value: 2.5
  min_value: 0
  default_min_value: 1
  default_max_value: 1.5
  wallOrientation: -0.5
checkpoint_08:
  armPosition:
  - alternative:
    - arm1: 0.0
      arm2: 0.05
      arm3: 0.12
      arm4: -1.32
      arm5: 1.63
    arm1: 2.7000013552373474
    arm2: 0.05006547217044144
    arm3: 0.12003444531268226
    arm4: 8.028932784220899e-05
    arm5: 0.94247648331981
  dial_properties:
    diameter: 0.105
  distanceToWall: -0.62
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.0
        arm2: 0.05
        arm3: 0.12
        arm4: 0.0
        arm5: 1.0
      arm1: 2.7
      arm2: 0.05
      arm3: 0.12
      arm4: 0.0
      arm5: 0.94
    endeffectorPosition:
    - frame_id: world
      q_w: 0.0
      q_x: 0.0
      q_y: 0.0
      q_z: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    flipper_angle: -0.75
    x: 0.2
    y: 1.1
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 1.1
    yaw: 1.0
  max_value: 16
  min_value: 0
  default_min_value: 1
  default_max_value: 2
  wallOrientation: -0.5
checkpoint_09:
  armPosition:
  - alternative:
    - arm1: 0.0
      arm2: 0.74
      arm3: 2.07
      arm4: -1.99
      arm5: 1.57
    arm1: 4.5571046092263146e-06
    arm2: -1.0641790706010932
    arm3: -2.3037766783644438
    arm4: -0.9599965377715121
    arm5: -1.6336250995788095
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.0
        arm2: 0.74
        arm3: 2.07
        arm4: -1.99
        arm5: 1.57
      arm1: 0.0
      arm2: -1.06
      arm3: -2.3
      arm4: -0.96
      arm5: -1.63
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0.0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: -0.2
    y: 0.75
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.6
    yaw: 1.0
  max_value: 100
  min_value: 0
  default_min_value: 10
  default_max_value: 100
  wallOrientation: -0.5
checkpoint_11:
  armPosition:
  - alternative:
    - arm1: 0.0
      arm2: -0.93
      arm3: -1.96
      arm4: -1.32
      arm5: 1.63
    arm1: -1.1370032175328504e-05
    arm2: -0.8502999034907059
    arm3: -1.786665768583755
    arm4: -0.9582651239272844
    arm5: -1.7592920711081872
  distanceToWall: -0.13
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.0
        arm2: -0.93
        arm3: -1.96
        arm4: -1.32
        arm5: 1.63
      arm1: -0.0
      arm2: -0.85
      arm3: -1.79
      arm4: -0.96
      arm5: -1.76
    endeffectorPosition:
    - frame_id: world
      q_w: 0.0
      q_x: 0.0
      q_y: 0.0
      q_z: 0.0
      x: 0.0
      y: 0.0
      z: 0.0
    flipper_angle: -0.75
    x: 0.0
    y: 1.3
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.5
    yaw: 1.0
  hotspot_properties:
    diameter: 0.1
  max_value: 2.5
  min_value: 0
  default_min_value: 60
  default_max_value: 100
  wallOrientation: -0.5
checkpoint_12:
  armPosition:
  - alternative:
    - arm1: 0.0
      arm2: -0.93
      arm3: -1.96
      arm4: -1.32
      arm5: 1.63
    arm1: 2.47105028527983e-06
    arm2: -0.9099854473691451
    arm3: -2.29999847862768
    arm4: -0.959998577062918
    arm5: -1.822124323203064
  distanceToWall: -0.13
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.0
        arm2: -0.93
        arm3: -1.96
        arm4: -1.32
        arm5: 1.63
      arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: -0.96
      arm5: -1.82
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.1
    y: 0.8
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.5
    yaw: 1.0
  hotspot_properties:
    diameter: 0.1
  max_value: 2.5
  min_value: 0
  default_min_value: 60
  default_max_value: 100
  wallOrientation: -0.5
checkpoint_13:
  armPosition:
  - alternative:
    - arm1: 0.0
      arm2: -0.93
      arm3: -1.96
      arm4: -1.32
      arm5: 1.63
    arm1: 5.3315279112453595e-05
    arm2: -0.9099171498441834
    arm3: -2.3000727651229598
    arm4: -0.9600027669074205
    arm5: -1.88495779323112
  distanceToWall: -0.13
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.0
        arm2: -0.93
        arm3: -1.96
        arm4: -1.32
        arm5: 1.63
      arm1: 0.0
      arm2: -0.91
      arm3: -2.3
      arm4: -0.96
      arm5: -1.88
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: -0.3
    y: 1.65
    yaw: 0.0
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.5
    yaw: 1.0
  hotspot_properties:
    diameter: 0.1
  max_value: 2.5
  min_value: 0
  default_min_value: 60
  default_max_value: 100
  wallOrientation: -0.5
save_area_center:
  armPosition:
  - arm1: 7.354215419752563e-06
    arm2: -0.9271407741536768
    arm3: -1.9576173875361809
    arm4: -1.3236541833458633
    arm5: 1.633627998213104
  distanceToWall: -0.13
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.0
        arm2: -0.93
        arm3: -1.96
        arm4: -1.32
        arm5: 1.63
      arm1: 2.7
      arm2: -0.93
      arm3: -1.96
      arm4: -1.32
      arm5: 1.63
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.0
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.0
    yaw: 0.5
  hotspot_properties:
    diameter: 0.1
  max_value: 2.5
  min_value: 0
  default_min_value: 60
  default_max_value: 100
  wallOrientation: -0.5
start_area_center:
  armPosition:
  - arm1: 7.354215419752563e-06
    arm2: -0.9271407741536768
    arm3: -1.9576173875361809
    arm4: -1.3236541833458633
    arm5: 1.633627998213104
  distanceToWall: -0.13
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.0
        arm2: -0.93
        arm3: -1.96
        arm4: -1.32
        arm5: 1.63
      arm1: 2.7
      arm2: -0.93
      arm3: -1.96
      arm4: -1.32
      arm5: 1.63
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.0
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.0
    yaw: 0.5
  hotspot_properties:
    diameter: 0.1
  max_value: 2.5
  min_value: 0
  default_min_value: 60
  default_max_value: 100
  wallOrientation: -0.5
step:
  armPosition:
  - arm1: 7.354215419752563e-06
    arm2: -0.9271407741536768
    arm3: -1.9576173875361809
    arm4: -1.3236541833458633
    arm5: 1.633627998213104
  distanceToWall: -0.13
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 0.0
        arm2: -0.93
        arm3: -1.96
        arm4: -1.32
        arm5: 1.63
      arm1: 2.7
      arm2: -0.93
      arm3: -1.96
      arm4: -1.32
      arm5: 1.63
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.0
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.0
    y: 0.0
    yaw: 0.5
  hotspot_properties:
    diameter: 0.1
  max_value: 2.5
  min_value: 0
  default_min_value: 60
  default_max_value: 100
  wallOrientation: -0.5
