checkpoint_01:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -0.19
  driveToPosition:
  - x: 0.7
    y: 0.0
    yaw: 0.5
  - x: 0.7
    y: 0.0
    yaw: 1.5
  max_value: 10
  min_value: 0
  wallOrientation: 1
checkpoint_02:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -1.1
  driveToPosition:
  - x: 1.8
    y: 0.0
    yaw: 0.5
  - x: 1.8
    y: 0.0
    yaw: 1.5
  max_value: 2.5
  min_value: 0
  wallOrientation: 1
checkpoint_03:
  dial_properties:
    diameter: 0.15
  distanceToWall: -1.1
  driveToPosition:
  - x: 0.0
    y: -1.8
    yaw: 0.0
  - x: 0.7
    y: -1.8
    yaw: 1.0
  max_value: 10
  min_value: 0
  wallOrientation: 0.5
checkpoint_04:
  distanceToWall: 0.19
  driveToPosition:
  - x: -0.4
    y: 0.0
    yaw: 0.5
  - x: -0.4
    y: 0.0
    yaw: 1.5
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0
checkpoint_05:
  distanceToWall: 0.055
  driveToPosition:
  - x: 0.0
    y: -0.4
    yaw: 0.0
  - x: 0.0
    y: -0.4
    yaw: 1.0
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_06:
  distanceToWall: 0.1
  driveToPosition:
  - x: 0.0
    y: -0.4
    yaw: 0.0
  - x: 0.0
    y: -0.4
    yaw: 1.0
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_07:
  dial_properties:
    diameter: 0.1
  distanceToWall: -0.13
  driveToPosition:
  - x: -0.0
    y: 0.5
    yaw: 0.0
  - x: 0.0
    y: 0.5
    yaw: 1.0
  max_value: 2.5
  min_value: 0
  wallOrientation: -0.5
checkpoint_08:
  dial_properties:
    diameter: 0.105
  distanceToWall: -0.62
  driveToPosition:
  - x: 0.0
    y: 1.1
    yaw: 0.0
  - x: 0.0
    y: 1.1
    yaw: 1.0
  max_value: 16
  min_value: 0
  wallOrientation: -0.5
checkpoint_09:
  distanceToWall: -0.28
  driveToPosition:
  - x: 1.8
    y: 0.0
    yaw: 0.5
  - x: 1.8
    y: 0.0
    yaw: 1.5
  max_value: 100
  min_value: 0
  wallOrientation: -0.5
