checkpoint_01:
  armPosition:
  - arm1: -1.5100054035346675
    arm2: 0.4239743911273841
    arm3: -1.9025616194885
    arm4: -2.357278073127927
    arm5: -1.0692365895530944
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - alternative:
      - arm1: 1.6
        arm2: 0.14
        arm3: -2.19
        arm4: -2.36
        arm5: -1.07
      arm1: -1.51
      arm2: 0.42
      arm3: -1.9
      arm4: -2.36
      arm5: -1.07
    endeffectorPosition:
    - frame_id: world
      q_w: 0.98
      q_x: 0
      q_y: -0.21
      q_z: -0.0
      x: -1.28
      y: -0.65
      z: -1.77
    - frame_id: base_link
      q_w: 0.98
      q_x: 0
      q_y: -0.21
      q_z: 0.0
      x: 0.13
      y: 0.06
      z: -0.94
    flipper_angle: -0.75
    x: 0.9
    y: -0.3
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 0.7
    y: -1.2
    yaw: 1.5
  max_value: 10
  min_value: 0
  wallOrientation: 1
checkpoint_02:
  armPosition:
  - arm1: -1.0681418642327056
    arm2: 0.5567713524402933
    arm3: -1.4974757823670863
    arm4: -2.2060869326393924
    arm5: 0.6911516775803515
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - alternative:
       - arm1: -2.95
         arm2: -0.91
         arm3: -2.30
         arm4: -0.96
         arm5: 1.13
    - arm1: -1.07
      arm2: 0.56
      arm3: -1.5
      arm4: -2.21
      arm5: 0.69
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 1.8
    y: -0.5
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 1.8
    y: 0.0
    yaw: 1.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 1.6
    y: -1.7
    yaw: 0.5
  - armPosition:
    - arm1: 0.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    endeffectorPosition:
    - frame_id: world
      q_w: 0
      q_x: 0
      q_y: 0
      q_z: 0
      x: 0
      y: 0
      z: 0
    flipper_angle: -0.75
    x: 1.6
    y: -1.7
    yaw: 1.5
  max_value: 2.5
  min_value: 0
  wallOrientation: 1

