checkpoint_01:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -0.19
  driveToPosition:
  - armPosition:
    - arm1: 1.0
      arm2: 0.0
      arm3: 1.23
      arm4: 0.0
      arm5: 0
    - arm1: 0.0
      arm2: 0
      arm3: 0.0
      arm4: 0
      arm5: 0
    x: -1.2
    y: -2.3
    yaw: 2.0
    flipper_angle: -0.75
  - armPosition:
    - arm1: 3.0
      arm2: 0.0
      arm3: 0.0
      arm4: 0.0
      arm5: 0
    - arm1: 1.0
      arm2: 0
      arm3: 0.0
      arm4: 0
      arm5: 0
    - arm1: 0.0
      arm2: 7.0
      arm3: 0
      arm4: 8.0
      arm5: 0
    x: 0.0
    y: 0.0
    yaw: 0.0
    flipper_angle: -0.75
  max_value: 10
  min_value: 0
  wallOrientation: 1
checkpoint_02:
  dial_properties:
    diameter: 0.1
  diameter: 3.14
  distanceToWall: -1.1
  driveToPosition:
  - armPosition:
    - arm1: 1.0
      arm2: 0.0
      arm3: 1.23
      arm4: 0.0
      arm5: 0
    - arm1: 0.0
      arm2: 0
      arm3: 0.0
      arm4: 0
      arm5: 0
    - arm1: 0.0
      arm2: 0
      arm3: 0
      arm4: 0
      arm5: 0
    x: -1.2
    y: -2.3
    yaw: 2.0
    flipper_angle: -0.75
  max_value: 2.5
  min_value: 0
  wallOrientation: 1
checkpoint_03:
  distanceToWall: 0.19
  driveToPosition:
  - armPosition:
    - arm1: 1.0
      arm2: 0.0
      arm3: 1.23
      arm4: 0.0
      arm5: 0
    - arm1: 2.0
      arm2: 0
      arm3: 0.0
      arm4: 0
      arm5: 0
    x: -1.2
    y: -2.3
    yaw: 2.0
    flipper_angle: -0.75
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0
checkpoint_04:
  distanceToWall: 0.055
  driveToPosition:
  - armPosition:
    - arm1: 1.0
      arm2: 0.0
      arm3: 1.23
      arm4: 0.0
      arm5: 0
    x: -1.2
    y: -2.3
    yaw: 2.0
    flipper_angle: -0.75
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_05:
  distanceToWall: 0.1
  driveToPosition:
  - armPosition:
    - arm1: 1.0
      arm2: 0.0
      arm3: 1.23
      arm4: 0.0
      arm5: 0
    x: -1.2
    y: -2.3
    yaw: 2.0
    flipper_angle: -0.75
  max_value: 1
  min_value: 0
  valve_properties:
    height: 0.01
    length: 0.13
    width: 0.03
  wallOrientation: 0.5
checkpoint_06:
  distanceToWall: -0.28
  driveToPosition:
  - armPosition:
    - arm1: 1.0
      arm2: 0.0
      arm3: 1.23
      arm4: 0.0
      arm5: 0
    x: -1.2
    y: -2.3
    yaw: 2.0
    flipper_angle: -0.75
  max_value: 100
  min_value: 0
  wallOrientation: -0.5
